// <auto-generated />
namespace SGITO_OBRAS.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropClassVenta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropClassVenta));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171739537_DropClassVenta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
